import { Question } from '../types';

export const INITIAL_QUESTIONS: Omit<Question, 'id'>[] = [
  // Quantitative Aptitude
  {
    subject: "Quantitative Aptitude",
    chapter: "Number Systems",
    question: "What is the unit digit in the product (7^95 - 3^58)?",
    optionA: "0",
    optionB: "4",
    optionC: "6",
    optionD: "7",
    answer: "B",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Quantitative Aptitude",
    chapter: "Number Systems",
    question: "If the number 91876y2 is completely divisible by 8, then what is the smallest value of y?",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    answer: "C",
    difficulty: "Easy",
    usageCount: 1,
    questionStatus: "Used",
    chapterCoverageScore: 7,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Quantitative Aptitude",
    chapter: "Percentage",
    question: "A student multiplied a number by 3/5 instead of 5/3. What is the percentage error in the calculation?",
    optionA: "44%",
    optionB: "54%",
    optionC: "64%",
    optionD: "74%",
    answer: "C",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 9,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Quantitative Aptitude",
    chapter: "Profit & Loss",
    question: "A trader sells two bullocks for Rs. 8,400 each, neither losing nor gaining in total. If he sold one at a gain of 20%, the other was sold at a loss of:",
    optionA: "20%",
    optionB: "18.18%",
    optionC: "14.28%",
    optionD: "16.67%",
    answer: "C",
    difficulty: "Hard",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 9,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Quantitative Aptitude",
    chapter: "Time & Work",
    question: "A can do a piece of work in 20 days and B in 30 days. They work together for 5 days and then A leaves. In how many days will B finish the remaining work?",
    optionA: "12 days",
    optionB: "15 days",
    optionC: "17.5 days",
    optionD: "20 days",
    answer: "C",
    difficulty: "Easy",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Quantitative Aptitude",
    chapter: "Algebra",
    question: "If x + 1/x = 5, then what is the value of x^3 + 1/x^3?",
    optionA: "110",
    optionB: "125",
    optionC: "140",
    optionD: "115",
    answer: "A",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 7,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },

  // Logical Reasoning
  {
    subject: "Logical Reasoning",
    chapter: "Series & Patterns",
    question: "Find the missing number in the sequence: 4, 18, 48, 100, 180, ?",
    optionA: "252",
    optionB: "294",
    optionC: "316",
    optionD: "348",
    answer: "B",
    difficulty: "Hard",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 9,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Logical Reasoning",
    chapter: "Coding-Decoding",
    question: "In a certain code language, 'COMPUTER' is written as 'RFUVQNPC'. How is 'MEDICINE' written in that same code?",
    optionA: "EOJDJEFM",
    optionB: "EOJDEJFM",
    optionC: "MFEJDJOE",
    optionD: "EOJDJMEN",
    answer: "A",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Logical Reasoning",
    chapter: "Blood Relations",
    question: "Pointing to a photograph, a woman says, 'He is the son of the only daughter of my father-in-law.' How is the man related to the woman?",
    optionA: "Son",
    optionB: "Brother-in-law",
    optionC: "Nephew",
    optionD: "Father",
    answer: "A",
    difficulty: "Easy",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Logical Reasoning",
    chapter: "Syllogisms",
    question: "Statements: All cats are dogs. Some dogs are birds. Conclusions: I. Some cats are birds. II. No cat is a bird.",
    optionA: "Only I follows",
    optionB: "Only II follows",
    optionC: "Either I or II follows",
    optionD: "Neither I nor II follows",
    answer: "C",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },

  // General Awareness
  {
    subject: "General Awareness",
    chapter: "Indian Polity",
    question: "Which Constitutional Amendment Act reduced the voting age from 21 years to 18 years in India?",
    optionA: "42nd Amendment",
    optionB: "44th Amendment",
    optionC: "61st Amendment",
    optionD: "73rd Amendment",
    answer: "C",
    difficulty: "Easy",
    usageCount: 2,
    questionStatus: "Used",
    chapterCoverageScore: 9,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "General Awareness",
    chapter: "Modern History",
    question: "Who was the Viceroy of India when the Quit India Movement was launched in 1942?",
    optionA: "Lord Linlithgow",
    optionB: "Lord Wavell",
    optionC: "Lord Mountbatten",
    optionD: "Lord Willingdon",
    answer: "A",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "General Awareness",
    chapter: "Geography",
    question: "Which Indian state shares the longest international boundary with Bangladesh?",
    optionA: "Assam",
    optionB: "West Bengal",
    optionC: "Meghalaya",
    optionD: "Tripura",
    answer: "B",
    difficulty: "Easy",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "General Awareness",
    chapter: "Indian Economy",
    question: "Which institution releases the 'Global Economic Prospects' report twice every year?",
    optionA: "International Monetary Fund (IMF)",
    optionB: "World Bank",
    optionC: "World Economic Forum (WEF)",
    optionD: "Asian Development Bank (ADB)",
    answer: "B",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 7,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "General Awareness",
    chapter: "General Science",
    question: "Which hormone is primarily responsible for regulating water reabsorption in human kidney tubules?",
    optionA: "Oxytocin",
    optionB: "Vasopressin (ADH)",
    optionC: "Thyroxine",
    optionD: "Insulin",
    answer: "B",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },

  // English Language
  {
    subject: "English Language",
    chapter: "Vocabulary",
    question: "Choose the word most SIMILAR in meaning to 'EPHEMERAL':",
    optionA: "Transient",
    optionB: "Eternal",
    optionC: "Substantial",
    optionD: "Perpetual",
    answer: "A",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "English Language",
    chapter: "Grammar",
    question: "Identify the part containing an error: 'Neither the principal nor the teachers (A) / was present (B) / at the annual function (C) / yesterday (D).'",
    optionA: "Neither the principal nor the teachers",
    optionB: "was present",
    optionC: "at the annual function",
    optionD: "No error",
    answer: "B",
    difficulty: "Easy",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 9,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "English Language",
    chapter: "Idioms & Phrases",
    question: "What does the idiom 'To burn the candle at both ends' mean?",
    optionA: "To waste money recklessly",
    optionB: "To work extremely hard from early morning until late night",
    optionC: "To destroy evidence",
    optionD: "To create double trouble",
    answer: "B",
    difficulty: "Easy",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 7,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },

  // Computer Knowledge
  {
    subject: "Computer Knowledge",
    chapter: "Networking",
    question: "Which layer of the OSI model is responsible for end-to-end reliability and flow control?",
    optionA: "Network Layer",
    optionB: "Data Link Layer",
    optionC: "Transport Layer",
    optionD: "Session Layer",
    answer: "C",
    difficulty: "Moderate",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 9,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  },
  {
    subject: "Computer Knowledge",
    chapter: "Cyber Security",
    question: "What type of attack involves an attacker placing themselves between two communicating parties to secretly intercept messages?",
    optionA: "Phishing",
    optionB: "Man-in-the-Middle (MitM)",
    optionC: "Denial of Service (DoS)",
    optionD: "SQL Injection",
    answer: "B",
    difficulty: "Easy",
    usageCount: 0,
    questionStatus: "Fresh",
    chapterCoverageScore: 8,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString()
  }
];
